name: Daily Data Update

on:
  schedule:
    - cron: "0 16 * * *"  # 7 PM UTC = 3 PM EDT - 16 is noon
  workflow_dispatch:     # Allow manual triggering too

jobs:
  run-script-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data creation script
        run: python Setlist_Creation/Get_Setlists.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Data/**/*.csv
          git commit -m "Daily data update" || echo "No changes to commit"
          git push
