name: Daily Data Update

permissions:
  contents: write

on:
  schedule:
    - cron: "55 23 * * *"  # 7:55 PM Eastern Time (23:55 UTC)
  workflow_dispatch:     # Allow manual triggering too

jobs:
  run-script-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml

      - name: Run data creation script
        env:
          PHISH_API_KEY: ${{ secrets.PHISH_API_KEY }}
        run: python Setlist_Creation/Get_Setlists.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Data/**/*.csv
          git commit -m "Daily data update" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/connorkitchings/Concerts.git HEAD:main
