name: Daily Setlist & Prediction Update

on:
  schedule:
    # Runs at 19:00 UTC (3pm ET) every day
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  update-data-and-predictions:
    runs-on: ubuntu-latest
    env:
      PHISH_API_KEY: ${{ secrets.PHISH_API_KEY }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install from requirements.txt if present, otherwise install common packages
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install numpy pandas scikit-learn xgboost
          fi

      - name: Run All Data Pipelines
        run: python scripts/run_all_pipelines.py

      - name: Run All Predictions
        run: python scripts/run_all_predict_todays.py

      - name: Commit and push collected data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/goose/collected/* data/phish/collected/* data/wsp/collected/* || echo "Nothing to add"
          git commit -m "[CI] Update collected band data [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
